---
version: "2.0"

services:
  pacman:
    image: yuravorobei/pacman-web
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    pacman:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    akash:
      attributes:
        host: akash
      pricing:
        pacman: 
          denom: uakt
          amount: 10000

deployment:
  pacman:
    akash:
      profile: pacman
      count: 1
